labwebprojeto/Models/Consola.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace labwebprojeto.Models
{
    [Table("Consola")]
    public class Consola
    {
        public Consola()
        {
            Jogos = new HashSet<Jogo>();
        }

        [Key]
        [Column("Id_Consola")]
        [Required(ErrorMessage = "Id Categoria is Required")]
        [DisplayName("ID Consola")]
        public int IdConsola { get; set; }

        [Column("nome")]
        [StringLength(50)]
        [DisplayName("Consola")]
        public string Nome { get; set; } = null!;

        [InverseProperty("IdConsolaNavigation")]
        public virtual ICollection<Jogo> Jogos { get; set; }
    }
}

labwebprojeto/Controllers/ConsolasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using labwebprojeto.Data;
using labwebprojeto.Models;
using Microsoft.AspNetCore.Authorization;

namespace labwebprojeto.Controllers
{
    [Authorize(Roles = "Func, Admin")]
    public class ConsolasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ConsolasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Consolas
        public async Task<IActionResult> Index(string searchString)
        {
            var consolas = from c in _context.Consolas
                             select c;

            if (!string.IsNullOrEmpty(searchString))
            {
                consolas = consolas.Where(j => j.Nome!.Contains(searchString));
                bool isEmpty = !consolas.Any();
                if (isEmpty)
                {
                    ViewData["empty_message"] = "There are no results...";
                }
                else
                {
                    ViewData["empty_message"] = "";
                }
            }
            return View(await consolas.ToListAsync());
        }

        // POST: Consolas/Create
        public async Task<IActionResult> Create([Bind("IdConsola,Nome")] Consola consola, string NewName)
        {
            consola.Nome = NewName;
            _context.Add(consola);
            await _context.SaveChangesAsync();
            return PartialView("Listing", _context.Consolas);
        }

        // GET: Consolas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Consolas == null)
            {
                return NotFound();
            }

            var consola = await _context.Consolas.FindAsync(id);
            if (consola == null)
            {
                return NotFound();
            }
            return PartialView("Edit", consola);
        }

        // POST: Consolas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Edit(int id, [Bind("IdConsola,Nome")] Consola consola)
        {
            if (id != consola.IdConsola)
            {
                return null;
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consola);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsolaExists(consola.IdConsola))
                    {
                        return null;
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return consola.Nome;
        }

        // GET: Consolas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else if (_context.Consolas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Consolas' is null.");
            }

            var consola = await _context.Consolas
                .FirstOrDefaultAsync(m => m.IdConsola == id);
            if (consola == null)
            {
                return NotFound();
            }

            _context.Consolas.Remove(consola);
            _context.SaveChanges();

            return PartialView("Listing", _context.Consolas);
        }


        private bool ConsolaExists(int id)
        {
          return _context.Consolas.Any(e => e.IdConsola == id);
        }
    }
}

labwebprojeto/Views/Consolas/Edit.cshtml
@model labwebprojeto.Models.Consola

<form asp-action="Edit" data-ajax="true" data-ajax-method="post"
      data-ajax-update="#Col_@Model.IdConsola" data-ajax-mode="replace">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="IdConsola" />
    <div>
        <input asp-for="Nome" />
        <span asp-validation-for="Nome" class="text-danger"></span>
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

labwebprojeto/Views/Consolas/Index.cshtml
@model IEnumerable<labwebprojeto.Models.Consola>

@{
    ViewData["Title"] = "Index";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        function Save() {
            $('.validation').remove();
            if ($('#inp').val() == '') 
            {
                alert('Please insert a value');
                return false;
            } 
        }
    </script>
</head>


<body id="bloquear-selecao" class="CategoriasBoddy">
    <main class="classmain">
        <section class="about-login">
            <div class="fartodisto2">
                <div class="row">
                    <div class="col-md-12 about-rightcena nopadding">
                        <h2>Index</h2>
                        <div class="searchbar">
                            <form class="d-flex" asp-controller="Consolas" asp-action="Index" method="get">
                                <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="SearchString">
                                <button class="btn btn-outline-success" type="submit" value="Filter">Search</button>
                            </form>
                        </div>

                        <label style="text-align:center;
                                    position:relative;
                                    left:13rem;
                                    top:8rem;">
                            @ViewData["empty_message"]
                        </label>

                        <table id="Tabela" class="table">
                            <thead>
                                <tr>
                                    <th>
                                        Consoles
                                    </th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td id="Col_@item.IdConsola">
                                            @Html.DisplayFor(modelItem => item.Nome)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.IdConsola"
                                           data-ajax="true" data-ajax-method="get"
                                           data-ajax-mode="replace" data-ajax-update="#Col_@item.IdConsola">

                                                Edit
                                            </a>
                                        </td>
                                        <td>
                                            <a asp-action="Delete" asp-route-id="@item.IdConsola"
                                           data-ajax="true" data-ajax-method="get"
                                           data-ajax-mode="replace" data-ajax-update="#Tabela"
                                           data-ajax-confirm="Are you sure?">
                                                Delete
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="butNew">
                            <form id="teste" asp-action="Create" data-ajax="true"
                                  data-ajax-method="post" data-ajax-mode="replace"
                                  data-ajax-update="#Tabela" data-ajax-success="sucesso"
                                  data-ajax-failure="falha">

                                <input id="inp" type="text" name="NewName" />
                                <input type="submit" value="Create" class="" onclick="Save()" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <script>
        function sucesso() {
            $("#inp").val("");
        }
    </script>
</body>

labwebprojeto/Views/Consolas/Listing.cshtml
@model IEnumerable<labwebprojeto.Models.Consola>

<table id="Tabela" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td id="Col_@item.IdConsola">
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdConsola"
                   data-ajax="true" data-ajax-method="get"
                   data-ajax-mode="replace" data-ajax-update="#Col_@item.IdConsola">

                        Edit
                    </a>
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.IdConsola"
                   data-ajax="true" data-ajax-method="get"
                   data-ajax-mode="replace" data-ajax-update="#Tabela"
                   data-ajax-confirm="Are you sure?">
                        Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>