labwebprojeto/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using labwebprojeto.Data;
using labwebprojeto.Models;
using labwebprojeto.Services.Interfaces;
using labwebprojeto.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace labwebprojeto.Controllers
{
    public class JogosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPhotoService _photoService;
        private readonly IEmailService _emailService;

        public JogosController(ApplicationDbContext context, 
            IPhotoService photoService, 
            IEmailService emailService)
        {
            _context = context;
            _photoService = photoService;
            _emailService = emailService;
        }

        // GET: Jogos
        public async Task<IActionResult> Index(string searchString)
        {
            var jogos = from j in _context.Jogos
                        select j;

            if (!String.IsNullOrEmpty(searchString))
            {
                jogos = jogos
                    .Where(j => j.Nome!.Contains(searchString))
                    .Include(j => j.IdCategoriaNavigation)
                    .Include(j => j.IdConsolaNavigation)
                    .Include(j => j.IdProdutoraNavigation);
                bool isEmpty = !jogos.Any();
                if (isEmpty)
                {
                    ViewData["empty_message"] = "There are no results...";
                }
                else
                {
                    ViewData["empty_message"] = "";
                }
                return View(jogos.ToList());
            }

            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome");
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome");
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome");

            var applicationDbContext = _context.Jogos.
                Include(j => j.IdCategoriaNavigation)
                .Include(j => j.IdConsolaNavigation)
                .Include(j => j.IdProdutoraNavigation);
            return View(await jogos.ToListAsync());
        }

        // GET: Jogos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogos
                .Include(j => j.IdCategoriaNavigation)
                .Include(j => j.IdConsolaNavigation)
                .Include(j => j.IdProdutoraNavigation)
                .FirstOrDefaultAsync(m => m.IdJogos == id);

            if (jogo == null)
            {
                return NotFound();
            }

            return View(jogo);
        }

        [Authorize(Roles = "Func, Admin")]
        public IActionResult Create()
        {
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome");
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome");
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome");
            return View();
        }

        // POST: Jogos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Func, Admin")]
        public async Task<IActionResult> Create(CreateJogoViewModel jogoVM)
        {
            if (ModelState.IsValid)
            {
                var result_pic = await _photoService.AddPhotoAsync(jogoVM.Foto);
                var result_pic1 = await _photoService.AddPhotoAsync(jogoVM.Foto1);
                var background = await _photoService.AddBackgroundAsync(jogoVM.Foto2);
                var jogo = new Jogo
                {
                    IdJogos = jogoVM.IdJogos,
                    Nome = jogoVM.Nome,
                    Foto = result_pic.Url.ToString(),
                    Foto1 = result_pic1.Url.ToString(),
                    Foto2 = background.Url.ToString(),
                    IdCategoria = jogoVM.IdCategoria,
                    IdConsola = jogoVM.IdConsola,
                    IdProdutora = jogoVM.IdProdutora,
                    Preco = Math.Round(jogoVM.Preco, 2),
                    Descricao = jogoVM.Descricao,
                    Descricao1 = jogoVM.Descricao1,
                };
                _context.Add(jogo);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Game Created Successfully";

                //Send Email
                var emailClient = GetClientEmails();
                var CatClients = GetClientFavs();
                var favourites = CatClients.Where(x => x.IdCategoria == jogoVM.IdCategoria);
                if(favourites.Any())
                {
                    foreach (var c in emailClient)
                    {
                        await _emailService.SendEmailAsync(c, "New Game - " + jogoVM.Nome, "New game added!");
                    }
                }

                return RedirectToAction("Index", "Home");
            }
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Game Not Created";
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome", jogoVM.IdCategoria);
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome", jogoVM.IdConsola);
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome", jogoVM.IdProdutora);

            return View(jogoVM);
        }

        // GET: Jogos/Edit/5
        [Authorize(Roles = "Func, Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogos.FindAsync(id);
            if (jogo == null)
            {
                return NotFound();
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome", jogo.IdCategoria);
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome", jogo.IdConsola);
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome", jogo.IdProdutora);
            return View(jogo);
        }

        // POST: Jogos/Edit/5
        [Authorize(Roles = "Func, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, 
            [Bind("IdJogos," +
            "Nome,Foto,Foto1," +
            "Foto2,IdCategoria," +
            "IdConsola,IdProdutora," +
            "Preco,Descricao,Descricao1")] Jogo jogo)
        {
            if (id != jogo.IdJogos) 
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(jogo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JogoExists(jogo.IdJogos))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome", jogo.IdCategoria);
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome", jogo.IdConsola);
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome", jogo.IdProdutora);
            return View(jogo);
        }

        // GET: Jogos/Delete/5
        [Authorize(Roles = "Func, Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else if (_context.Jogos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categoria' is null.");
            }

            var jogos = await _context.Jogos
                .FirstOrDefaultAsync(m => m.IdJogos == id);
            if (jogos == null)
            {
                return NotFound();
            }

            _context.Jogos.Remove(jogos);
            _context.SaveChanges();

            return PartialView("Listing", _context.Jogos);
        }

        private bool JogoExists(int id)
        {
          return _context.Jogos.Any(e => e.IdJogos == id);
        }


        /*--------CATEGORIAS*---------*/
        public async Task<IActionResult> IndexCategorias(int? id)
        {
            var jogos = (from j in _context.Jogos
                         select j)
                         .Where(x => x.IdCategoria == id);
            return View(await jogos.ToListAsync());
        }

        /*--------PRODUTORAS*---------*/
        public IActionResult IndexProdutoras(int? id)
        {
            var jogos = (from j in _context.Jogos
                         select j)
                         .Where(x => x.IdProdutora == id);
            return View(jogos.ToList());
        }

        /*--------CONSOLAS*---------*/
        public async Task<IActionResult> IndexConsolas(int? id)
        {
            var jogos = (from j in _context.Jogos
                         select j)
                         .Where(x => x.IdConsola == id);
            return View(await jogos.ToListAsync());
        }

        /*--------CONSOLAS*---------*/
        public IQueryable<string> GetClientEmails()
        {

labwebprojeto/Controllers/JoinController.cs
using labwebprojeto.Data;
using labwebprojeto.Models;
using labwebprojeto.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace labwebprojeto.Controllers
{
    [AllowAnonymous]
    public class JoinController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JoinController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string str1, string str2, string str3)
        {

            var cat = (from c in _context.Categoria
                       select c);

            var cons = (from c in _context.Consolas
                       select c);

            var prod = (from p in _context.Produtoras
                    select p);
            
            if(!String.IsNullOrEmpty(str1))
            {
               cat = cat.Where(x => x.Nome.Contains(str1));


                bool isEmpty = !cat.Any();
                if (isEmpty)
                {
                    //Mostrar Mensagem com ViewData
                }
            }

            if (!String.IsNullOrEmpty(str2))
            {

                cons = cons.Where(x => x.Nome.Contains(str2));

                bool isEmpty = !cons.Any();
                if (isEmpty)
                {
                    //Mostrar Mensagem com ViewData
                }
            }

            if (!String.IsNullOrEmpty(str3))
            {
                prod = prod.Where(x => x.Nome.Contains(str3));

                bool isEmpty = !prod.Any();
                if (isEmpty)
                {
                    //Mostrar Mensagem com ViewData
                }
            }

            var tuple = new Tuple<List<Categoria>, List<Consola>, List<Produtora>>(cat.ToList(), cons.ToList(), prod.ToList());
            return View(tuple);
        }
    }
}

labwebprojeto/Views/Join/Index.cshtml
@using labwebprojeto.Models;
@model Tuple<List<Categoria>, List<Consola>, List<Produtora>>


<body id="bloquear-selecao" class="joinclass">

    <main class="temdedar">
        <div>
            
        <input  id="tab1" type="radio" name="tabs" checked>
        <label for="tab1">Categories</label>

            <input   id="tab2" type="radio" name="tabs">
            <label for="tab2">Consoles</label>

            <input  id="tab3" type="radio" name="tabs">
        <label for="tab3">Producers</label>
        

        <section  id="content1">
            <p>
                <form class="d-flex" asp-controller="Join" asp-action="Index" method="get">
                    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="str1">
                    <button class="btn btn-outline-success" type="submit" value="Filter">Search</button>
                </form>
                @foreach (Categoria cat in Model.Item1)
                {
                    <div class="seraserasera">
                        <button class="btn btn-outline-success" type="submit" value="Filter">
                            <a asp-controller="Jogos" asp-action="IndexCategorias" asp-route-id="@cat.IdCategoria">@Html.DisplayFor(modelItem => cat.Nome)</a>
                        </button>
                        <br>
                    </div>
                }
            </p>
            
        </section>

        <section id="content2">
            <p>
                <form class="d-flex" asp-controller="Join" asp-action="Index" method="get">
                    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="str2">
                    <button class="btn btn-outline-success" type="submit" value="Filter">Search</button>
                </form>
                @foreach (Consola cons in Model.Item2)
                {
                    <div class="seraserasera">
                        <button class="btn btn-outline-success" type="submit" value="Filter">
                            <a asp-controller="Jogos" asp-action="IndexCategorias" asp-route-id="@cons.IdConsola">@Html.DisplayFor(modelItem => cons.Nome)</a>
                        </button>
                        <br>
                    </div>
                }
            </p>
            
        </section>

        <section id="content3">
            <p>
                <form class="d-flex" asp-controller="Join" asp-action="Index" method="get">
                    <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="str3">
                    <button class="btn btn-outline-success" type="submit" value="Filter">Search</button>
                </form>
                @foreach (Produtora prod in Model.Item3)
                {
                    <div class="seraserasera">
                        <button class="btn btn-outline-success" type="submit" value="Filter">
                            <a asp-controller="Jogos" asp-action="IndexCategorias" asp-route-id="@prod.IdProdutora">@Html.DisplayFor(modelItem => prod.Nome)</a>
                        </button>
                        <br>
                    </div>
                }
            </p>
            
        </section>
        </div>
    </main>
</body>