labwebprojeto/Controllers/FavoritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using labwebprojeto.Data;
using labwebprojeto.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using System.Security.Claims;
using CloudinaryDotNet;
using labwebprojeto.ViewModels;
using Syncfusion.EJ2.Buttons;
using Syncfusion.EJ2.Linq;
using Microsoft.AspNetCore.Authorization;

namespace labwebprojeto.Controllers
{
    [Authorize]
    public class FavoritosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FavoritosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Favoritos

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var nome = GetCurrentUserName();
            ViewData["userNome"] = nome;

            var applicationDbContext = _context.Favoritos
                .Include(f => f.IdCategoriaNavigation)
                .Include(f => f.IdUtilizadorNavigation)
                .Where(f => f.IdUtilizadorNavigation.IdUtilizador
                == GetCurrentUserID());

            bool isEmpty = !applicationDbContext.Any();
            if (isEmpty)
            {
                ViewData["empty_message"] = "There are no results...";
            }
            else
            {
                ViewData["empty_message"] = "";
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Favoritos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Favoritos == null)
            {
                return NotFound();
            }
            var userID = GetCurrentUserID();

            var jogosUti = (from f in _context.Favoritos
                            join u in _context.Utilizadors
                            on f.IdUtilizador equals userID
                            select f)
                            .Where(x=>x.IdFavorito == id)
                            .Distinct();

            var jogos = from j in _context.Jogos
                        join f in jogosUti
                        on j.IdCategoria equals f.IdCategoria
                        select j.Nome;

            ViewData["ListaJogos"] = jogos;

            var favorito = await _context.Favoritos
                .Include(f => f.IdCategoriaNavigation)
                .Include(f => f.IdUtilizadorNavigation)
                .FirstOrDefaultAsync(m => m.IdFavorito == id);
            if (favorito == null)
            {
                return NotFound();
            }

            return View(favorito);
        }

        // GET: Favoritos/Create
        public IActionResult Create()
        {
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome");
            return View();
        }

        // POST: Favoritos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateFavoritoViewModel favVM)
        {
            var user = GetCurrentUser();
            var userID = GetCurrentUserID();
            var userName = GetCurrentUserName();

            if (ModelState.IsValid)
            {
                var fav = new Favorito
                {
                    IdFavorito = favVM.IdFavorito,
                    IdCategoria = favVM.IdCategoria,
                    IdUtilizador = userID
                };
                userID = favVM.IdUtilizador;

                _context.Add(fav);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome", favVM.IdCategoria);
            ViewData["NomeUtilizador"] = userName;
            return View(favVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else if (_context.Favoritos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Consolas' is null.");
            }

            var fav = await _context.Favoritos
                .FirstOrDefaultAsync(m => m.IdFavorito == id);
            if (fav == null)
            {
                return NotFound();
            }

            _context.Favoritos.Remove(fav);
            _context.SaveChanges();

            return PartialView("Listing", _context.Favoritos);
        }

        private bool FavoritoExists(int id)
        {
          return _context.Favoritos.Any(e => e.IdFavorito == id);
        }

        /*------------USER---------------*/
        public IQueryable<Utilizador> GetCurrentUser()
        {
            var user = (from u in _context.Utilizadors
                        select u);
            //Fetch Actual Identity
            var identity = (ClaimsIdentity)User.Identity;

            //Fetch of First User With Name Specified - returns ID
            //var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //Email of Identity
            var claims = identity.Name;

            //Utilizador objet where Email = Actual Email
            var userlog = user.Where(x => x.Nome.Equals(claims));

            return (userlog);
        }

        public int GetCurrentUserID()
        {
            var user = (from u in _context.Utilizadors
                        select u);
            //Fetch Actual Identity
            var identity = (ClaimsIdentity)User.Identity;

            //Fetch of First User With Name Specified - returns ID
            //var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //Email of Identity
            var claims = identity.Name;

            //Utilizador objet where Nome = Actual Nome
            var userlog = user.Where(x => x.Nome.Equals(claims));

            var userID = (from u in _context.Utilizadors
                         join i in userlog
                         on u.IdUtilizador equals i.IdUtilizador
                         select i.IdUtilizador).First();
            return (userID);
        }

        public string? GetCurrentUserName()
        {
            var user = (from u in _context.Utilizadors
                        select u);
            //Fetch Actual Identity
            var identity = (ClaimsIdentity)User.Identity;

            //Email of Identity
            var claims = identity.Name;

            return claims;
        }

    }
}

labwebprojeto/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using labwebprojeto.Data;
using labwebprojeto.Models;
using labwebprojeto.Services.Interfaces;
using labwebprojeto.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace labwebprojeto.Controllers
{
    public class JogosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPhotoService _photoService;
        private readonly IEmailService _emailService;

        public JogosController(ApplicationDbContext context, 
            IPhotoService photoService, 
            IEmailService emailService)
        {
            _context = context;
            _photoService = photoService;
            _emailService = emailService;
        }

        // GET: Jogos
        public async Task<IActionResult> Index(string searchString)
        {
            var jogos = from j in _context.Jogos
                        select j;

            if (!String.IsNullOrEmpty(searchString))
            {
                jogos = jogos
                    .Where(j => j.Nome!.Contains(searchString))
                    .Include(j => j.IdCategoriaNavigation)
                    .Include(j => j.IdConsolaNavigation)
                    .Include(j => j.IdProdutoraNavigation);
                bool isEmpty = !jogos.Any();
                if (isEmpty)
                {
                    ViewData["empty_message"] = "There are no results...";
                }
                else
                {
                    ViewData["empty_message"] = "";
                }
                return View(jogos.ToList());
            }

            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome");
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome");
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome");

            var applicationDbContext = _context.Jogos.
                Include(j => j.IdCategoriaNavigation)
                .Include(j => j.IdConsolaNavigation)
                .Include(j => j.IdProdutoraNavigation);
            return View(await jogos.ToListAsync());
        }

        // GET: Jogos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogos
                .Include(j => j.IdCategoriaNavigation)
                .Include(j => j.IdConsolaNavigation)
                .Include(j => j.IdProdutoraNavigation)
                .FirstOrDefaultAsync(m => m.IdJogos == id);

            if (jogo == null)
            {
                return NotFound();
            }

            return View(jogo);
        }

        [Authorize(Roles = "Func, Admin")]
        public IActionResult Create()
        {
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome");
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome");
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome");
            return View();
        }

        // POST: Jogos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Func, Admin")]
        public async Task<IActionResult> Create(CreateJogoViewModel jogoVM)
        {
            if (ModelState.IsValid)
            {
                var result_pic = await _photoService.AddPhotoAsync(jogoVM.Foto);
                var result_pic1 = await _photoService.AddPhotoAsync(jogoVM.Foto1);
                var background = await _photoService.AddBackgroundAsync(jogoVM.Foto2);
                var jogo = new Jogo
                {
                    IdJogos = jogoVM.IdJogos,
                    Nome = jogoVM.Nome,
                    Foto = result_pic.Url.ToString(),
                    Foto1 = result_pic1.Url.ToString(),
                    Foto2 = background.Url.ToString(),
                    IdCategoria = jogoVM.IdCategoria,
                    IdConsola = jogoVM.IdConsola,
                    IdProdutora = jogoVM.IdProdutora,
                    Preco = Math.Round(jogoVM.Preco, 2),
                    Descricao = jogoVM.Descricao,
                    Descricao1 = jogoVM.Descricao1,
                };
                _context.Add(jogo);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Game Created Successfully";

                //Send Email
                var emailClient = GetClientEmails();
                var CatClients = GetClientFavs();
                var favourites = CatClients.Where(x => x.IdCategoria == jogoVM.IdCategoria);
                if(favourites.Any())
                {
                    foreach (var c in emailClient)
                    {
                        await _emailService.SendEmailAsync(c, "New Game - " + jogoVM.Nome, "New game added!");
                    }
                }

                return RedirectToAction("Index", "Home");
            }
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Game Not Created";
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome", jogoVM.IdCategoria);
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome", jogoVM.IdConsola);
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome", jogoVM.IdProdutora);

            return View(jogoVM);
        }

        // GET: Jogos/Edit/5
        [Authorize(Roles = "Func, Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jogos == null)
            {
                return NotFound();
            }

            var jogo = await _context.Jogos.FindAsync(id);
            if (jogo == null)
            {
                return NotFound();
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome", jogo.IdCategoria);
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome", jogo.IdConsola);
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome", jogo.IdProdutora);
            return View(jogo);
        }

        // POST: Jogos/Edit/5
        [Authorize(Roles = "Func, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, 
            [Bind("IdJogos," +
            "Nome,Foto,Foto1," +
            "Foto2,IdCategoria," +
            "IdConsola,IdProdutora," +
            "Preco,Descricao,Descricao1")] Jogo jogo)
        {
            if (id != jogo.IdJogos) 
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(jogo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JogoExists(jogo.IdJogos))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Nome", jogo.IdCategoria);
            ViewData["IdConsola"] = new SelectList(_context.Consolas, "IdConsola", "Nome", jogo.IdConsola);
            ViewData["IdProdutora"] = new SelectList(_context.Produtoras, "IdProdutora", "Nome", jogo.IdProdutora);
            return View(jogo);
        }

        // GET: Jogos/Delete/5
        [Authorize(Roles = "Func, Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else if (_context.Jogos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categoria' is null.");
            }

            var jogos = await _context.Jogos
                .FirstOrDefaultAsync(m => m.IdJogos == id);
            if (jogos == null)
            {
                return NotFound();
            }

            _context.Jogos.Remove(jogos);
            _context.SaveChanges();

            return PartialView("Listing", _context.Jogos);
        }

        private bool JogoExists(int id)
        {
          return _context.Jogos.Any(e => e.IdJogos == id);
        }


        /*--------CATEGORIAS*---------*/
        public async Task<IActionResult> IndexCategorias(int? id)
        {
            var jogos = (from j in _context.Jogos
                         select j)
                         .Where(x => x.IdCategoria == id);
            return View(await jogos.ToListAsync());
        }

        /*--------PRODUTORAS*---------*/
        public IActionResult IndexProdutoras(int? id)
        {
            var jogos = (from j in _context.Jogos
                         select j)
                         .Where(x => x.IdProdutora == id);
            return View(jogos.ToList());
        }

        /*--------CONSOLAS*---------*/
        public async Task<IActionResult> IndexConsolas(int? id)
        {
            var jogos = (from j in _context.Jogos
                         select j)
                         .Where(x => x.IdConsola == id);
            return View(await jogos.ToListAsync());
        }

        /*--------CONSOLAS*---------*/
        public IQueryable<string> GetClientEmails()
        {

labwebprojeto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - labwebprojeto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/labwebprojeto.styles.css" asp-append-version="true" />

    <!-- Syncfusion ASP.NET Core controls styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.4.38/bootstrap5-dark.css" />

    <!-- Syncfusion ASP.NET Core controls scripts -->
    <script src="https://cdn.syncfusion.com/ej2/20.4.38/dist/ej2.min.js"></script>

    <!-- Add Toastr Notifications -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#1C1C1C">
            <div class="container-fluid">
                <a class="navbar-brand" href="/Home/Index">Can't Stop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        @if(User.IsInRole("Admin"))
                        {
                            <li>
                                <a href="/Utilizadores/Index" class="nav-link text-light">Users</a>
                            </li>
                        }
                        @if ((User.IsInRole("Admin")))
                        {
                            <li>
                                <a href="/Join/Index" class="nav-link text-light">Search</a>
                            </li>
                            <li>
                                <a href="/Categorias" class="nav-link text-light">Categories</a>
                            </li>
                            <li>
                                <a href="/Consolas" class="nav-link text-light">Consoles</a>
                            </li>
                            <li>
                                <a href="/Produtoras" class="nav-link text-light">Producers</a>
                            </li>
                            <li>
                                <a href="/Favoritos" class="nav-link text-light">Favorites</a>
                            </li>
                            <li>
                                <a href="/Compras" class="nav-link text-light">Library</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Jogos" asp-action="Index">Inventory</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Jogos" asp-action="Create">Create Game</a>
                            </li>
                        }
                        @if(User.IsInRole("Func"))
                        {
                            <li>
                                <a href="/Join/Index" class="nav-link text-light">Search</a>
                            </li>
                            <li>
                                <a href="/Favoritos" class="nav-link text-light">Favorites</a>
                            </li>
                            <li>
                                <a href="/Compras" class="nav-link text-light">Library</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Jogos" asp-action="Index">Inventory</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Jogos" asp-action="Create">Create Game</a>
                            </li>
                        }
                        @if(User.IsInRole("Client"))
                        {
                            <li>
                                <a href="/Join/Index" class="nav-link text-light">Search</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Compras" asp-action="Index">Library</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Favoritos" asp-action="Index">Favorites</a>
                            </li>

                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a href="/Join/Index" class="nav-link text-light">Search</a>
                            </li>
                        }
                    </ul>
                </div>

                <div class="justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        @if ((User.IsInRole("Admin")) || (User.IsInRole("Func")) || (User.IsInRole("Client")))
                        {
                        <li>
                            <a href="/Identity/Account/Logout" class="nav-link text-light justify-content-end">Logout</a>
                        </li>
                        <li>
                            <a href="/Identity/Account/Manage" class="nav-link text-light justify-content-end">Profile</a>
                        </li>
                        }
                        else {
                        <li>
                            <a href="/Identity/Account/Login" class="nav-link text-light justify-content-end">Login</a>
                        </li>
                        <li>
                            <a href="/Identity/Account/Register" class="nav-link text-light justify-content-end">Sign up</a>
                        </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ajax/jquery.unobtrusive-ajax.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <!-- Syncfusion Script Manager -->
    <ejs-scripts></ejs-scripts>
</body>
</html>

labwebprojeto/Views/Shared/_Notification.cshtml
@{
    Layout = null;
}

@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}
@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}