labwebprojeto/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using labwebprojeto.Data;
using labwebprojeto.Models;
using Microsoft.AspNetCore.Authorization;

namespace labwebprojeto.Controllers
{
    [Authorize(Roles="Func, Admin")]
    public class CategoriasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index(string searchString)
        {
            var categorias = from c in _context.Categoria
                             select c;

            if (!string.IsNullOrEmpty(searchString))
            {
                categorias = categorias
                    .Where(j => j.Nome!.Contains(searchString));
                bool isEmpty = !categorias.Any();
                if (isEmpty)
                {
                    ViewData["empty_message"] = "There are no results...";
                }
                else
                {
                    ViewData["empty_message"] = "";
                }
            }
            return View(await categorias.ToListAsync());
        }

        // POST: Categorias/Create
        public async Task<IActionResult> Create([Bind("IdCategoria,Nome")] Categoria categoria, string NewName)
        {
            categoria.Nome = NewName;
            _context.Add(categoria);
            await _context.SaveChangesAsync();
            return PartialView("Listing", _context.Categoria);
        }

        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categoria == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return PartialView("Edit", categoria);
        }

        // POST: Categorias/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Edit(int id, [Bind("IdCategoria,Nome")] Categoria categoria)
        {
            if (id != categoria.IdCategoria)
            {
                return null;
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.IdCategoria))
                    {
                        return null;
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return categoria.Nome;
        }

        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else if(_context.Categoria == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categoria' is null.");
            }

            var categoria = await _context.Categoria
                .FirstOrDefaultAsync(m => m.IdCategoria == id);
            if (categoria == null)
            {
                return NotFound();
            }

            _context.Categoria.Remove(categoria);
            _context.SaveChanges();

            return PartialView("Listing", _context.Categoria);
        }

        private bool CategoriaExists(int id)
        {
          return _context.Categoria.Any(e => e.IdCategoria == id);
        }
    }
}

labwebprojeto/Controllers/UtilizadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using labwebprojeto.Data;
using labwebprojeto.Models;
using Microsoft.AspNetCore.Authorization;

namespace labwebprojeto.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UtilizadoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UtilizadoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Utilizadores
        public async Task<IActionResult> Index(string searchString)
        {
            var list = (from u in _context.Utilizadors
                        select u)
                       .Where(x => x.IsFunc || x.IsAdmin == true);

            if (!string.IsNullOrEmpty(searchString))
            {
                list = list
                    .Where(j => j.Nome!.Contains(searchString));
                bool isEmpty = !list.Any();
                if (isEmpty)
                {
                    ViewData["empty_message"] = "There are no results...";
                }
                else
                {
                    ViewData["empty_message"] = "";
                }
            }
                return View(await list.ToListAsync());
        }

        // GET: Utilizadores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Utilizadors == null)
            {
                return NotFound();
            }

            var utilizador = await _context.Utilizadors
                .FirstOrDefaultAsync(m => m.IdUtilizador == id);
            if (utilizador == null)
            {
                return NotFound();
            }

            return View(utilizador);
        }
    }
}

labwebprojeto/Views/Utilizadores/Details.cshtml
@model labwebprojeto.Models.Utilizador

@{
    ViewData["Title"] = "Details";
}


<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>

<body id="bloquear-selecao" class="CategoriasBoddy">
    <main class="classmain">
        <section class="about-checkoutlista">
            <div class="checkoutlista">
                <div class="row">
                    <div class="col-md-12 about-rightcena nopadding">
                        <h2>Utilizador</h2>
                        <div class="searchbar">
                            <form class="d-flex" asp-controller="Categorias" asp-action="Index" method="get">
                                <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="SearchString">
                                <button class="btn btn-outline-success" type="submit" value="Filter">Search</button>
                            </form>
                        </div>

<div class="detailsuti">
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>

        @if(User.IsInRole("Func"))
        {
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        }
    </dl>
</div>
<div class="paratrocar">
    <a asp-action="Index">Back to List</a>
</div>
                        
                    </div>
                </div>
            </div>
        </section>
    </main>
</body>

labwebprojeto/Views/Utilizadores/Index.cshtml
@model IEnumerable<labwebprojeto.Models.Utilizador>

@{
    ViewData["Title"] = "Index";
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        function Save() {
            $('.validation').remove();
            if ($('#inp').val() == '') {
                alert('Please insert a value');
                return false;
            }
        }
    </script>
</head>

<body id="bloquear-selecao" class="CategoriasBoddy">
    <main class="classmain">
        <section class="about-login">
            <div class="fartodisto2">
                <div class="row">
                    <div class="col-md-12 about-rightcena nopadding">
                        <h2>Index</h2>
                        <div class="searchbar">
                            <form class="d-flex" asp-controller="Utilizadores" asp-action="Index" method="get">
                                <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="SearchString">
                                <button class="btn btn-outline-success" type="submit" value="Filter">Search</button>
                            </form>
                        </div>

                        <label style="text-align:center;
                                    position:relative;
                                    left:13rem;
                                    top:8rem;">
                            @ViewData["empty_message"]
                        </label>

                        <table id="Tabela" class="table">
                            <thead>
                                <tr>
                                    <th>
                                        Role
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @if (item.IsAdmin)
                                            {
                                                <label>Admin</label>
                                            }
                                            @if (item.IsFunc)
                                            {
                                                <label>Employee</label>
                                            }
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Nome)
                                        </td>
                                        <td>
                                            <a asp-action="Details" asp-route-id="@item.IdUtilizador">Details</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        
                        <div class="butNew2">
                            <button onclick="window.location.href='/Identity/Account/Register'" > Add new User</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <script>
        function sucesso() {
            $("#inp").val("");
        }
    </script>
</body>

labwebprojeto/Views/Utilizadores/Listing.cshtml
@model IEnumerable<labwebprojeto.Models.Utilizador>

<table id="Tabela" class="table">
    <thead>
        <tr>
            <th>
                Role
            </th>
            <th>
                Name
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.IsAdmin)
                    {
                        <label>Admin</label>
                    }
                    @if (item.IsFunc)
                    {
                        <label>Employee</label>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                @if(User.IsInRole("Admin"))
                {
                <td>
                    <a asp-action="Details" asp-route-id="@item.IdUtilizador">
                        Details</a>
                </td>  
                }
            </tr>
        }
    </tbody>
</table>